name: install-ng-and-build
on: [push]
jobs:
  install-ng-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g @angular/cli
      - run: ng new gh-app --defaults=true
      - run: ng build
      - run: ng -v